// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"wasdKeyMZ","status":true,"description":"It is a plugin that corresponds to the wasd move.","parameters":{}}
];
